# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Ayesha Akhtar <ayesha@ankur.org.bd>, 2012.
# Mahay Alam Khan <mak@ankur.org.bd>, 2012.
# Miroslav Suchý <msuchy@redhat.com>, 2011.
# Newton Baidya <newton@ankur.org.bd>, 2012.
# Progga <progga@BengaLinux.Org>, 2004.
# Robin Mehdee <robin@ankur.org.bd>, 2012.
# Runa Bhattacharjee <runab@redhat.com>, 2004.
# Salahuddin <salahuddin66@gmail.com>, 2004.
# Samia Niamatullah <mailsamia2001@yahoo.com>, 2005.
# Ayesha Akhtar <ayesha@ankur.org.bd>, 2012
# Mahay Alam Khan <mak@ankur.org.bd>, 2012
# Miroslav Suchý <msuchy@redhat.com>, 2011
# newton <newton@ankur.org.bd>, 2012
# Progga <progga@BengaLinux.Org>, 2004
# Robin Mehdee <robin@ankur.org.bd>, 2012
# runab <runab@redhat.com>, 2004
# Salahuddin <salahuddin66@gmail.com>, 2004
# Samia Niamatullah <mailsamia2001@yahoo.com>, 2005
# Jan Dobes <jdobes@redhat.com>, 2016. #zanata
# Jiri Dostal <jdostal@redhat.com>, 2018. #zanata
msgid ""
msgstr ""
"Project-Id-Version: Spacewalk\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-04-08 15:54+0200\n"
"PO-Revision-Date: 2018-03-16 10:59+0000\n"
"Last-Translator: Copied by Zanata <copied-by-zanata@zanata.org>\n"
"Language-Team: Bengali (http://www.transifex.com/projects/p/spacewalk/"
"language/bn/)\n"
"Language: bn\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: Zanata 4.6.2\n"

#: ../src/up2date_client/capabilities.py:94
#, python-format
msgid ""
"This client requires the server to support %s, which the current server does "
"not support"
msgstr ""
"এই ক্লায়েন্টের জন্য সার্ভারের দ্বারা %s-র সমর্থিত হওয়া আবশ্যক। বর্তমান সার্ভারে এটি "
"সমর্থিত নয়।"

#: ../src/up2date_client/config.py:162
#, python-format
msgid "%s was not found"
msgstr "%s পাওয়া যায়নি"

#: ../src/up2date_client/rpcServer.py:56
msgid "Error: Server Unavailable. Please try later."
msgstr "ত্রুটি: সর্ভার বিদ্যমান নয়। অনুগ্রহপূর্বক পরে চেষ্টা করুন।"

#: ../src/up2date_client/rpcServer.py:182
#, fuzzy
msgid "ERROR: can not find server CA file"
msgstr "ত্রুটি: RHNS CA ফাইল খুঁজে পাওয়া যাচ্ছে না।"

#: ../src/up2date_client/rpcServer.py:220
msgid "Connection aborted by the user"
msgstr "ব্যবহারকারীর দ্বারা সংযোগ বিচ্ছিন্ন করা হয়েছে"

#: ../src/up2date_client/rpcServer.py:268
msgid "Server has refused connection due to high load"
msgstr "সার্ভারে অতিরিক্ত চাপের কারণে সার্ভার সংযোগ প্রত্যাখান করেছে।"

#: ../src/up2date_client/up2dateErrors.py:47
#: ../src/up2date_client/up2dateErrors.py:80
#, python-format
msgid "class %s has no attribute '%s'"
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:107
msgid "RPM error.  The message was:\n"
msgstr "RPM জড়িত ত্রুটি।  বার্তাটি ছিল:\n"

#: ../src/up2date_client/up2dateErrors.py:114
msgid "Password error. The message was:\n"
msgstr "পাসওয়ার্ড সংক্রান্ত সমস্যা।  বার্তাটি ছিল:\n"

#: ../src/up2date_client/up2dateErrors.py:118
msgid "RPM dependency error. The message was:\n"
msgstr "RPM নির্ভরতা সংক্রান্ত সমস্যা। বার্তাটি:\n"

#: ../src/up2date_client/up2dateErrors.py:128
msgid "Error communicating with server. The message was:\n"
msgstr "সার্ভারের সাথে যোগাযোগে সমস্যা। বার্তাটি ছিল:\n"

#: ../src/up2date_client/up2dateErrors.py:135
msgid "File Not Found: \n"
msgstr "ফাইল পাওয়া যায়নি: \n"

#: ../src/up2date_client/up2dateErrors.py:142
msgid "Delay error from server.  The message was:\n"
msgstr "সার্ভারে বিলম্ব সংক্রান্ত সমস্যা হয়েছে।  বার্তাটি ছিল:\n"

#: ../src/up2date_client/up2dateErrors.py:178
msgid "Error validating data at server:\n"
msgstr "সার্ভারের তথ্যের বৈধতা যাচাইয়ে সমস্যা:\n"

#: ../src/up2date_client/up2dateErrors.py:191
msgid ""
"\n"
"Red Hat Network Classic is not supported.\n"
"    "
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:197
msgid "The installation number is invalid"
msgstr "সংস্থাপন সংখ্যাটি অকার্যকর"

#: ../src/up2date_client/up2dateErrors.py:200
msgid "Error parsing the oemInfo file at field:\n"
msgstr "oemInfo ফাইল পার্স করার সময় এই ক্ষেত্রে সমস্যা হয়েছে:\n"

#: ../src/up2date_client/up2dateErrors.py:227
msgid "Network error: "
msgstr "নেটওয়ার্কের ত্রুটি:"

#: ../src/up2date_client/up2dateErrors.py:295
msgid ""
"\n"
"    Your organization does not have enough Management entitlements to "
"register this\n"
"    system. Please notify your organization administrator of this error.\n"
"    You should be able to register this system after your organization frees "
"existing\n"
"    or purchases additional entitlements. Additional entitlements may be "
"purchased by your\n"
"    organization administrator in the SUSE Customer Center.\n"
"\n"
"    A common cause of this error code is due to having mistakenly setup an\n"
"    Activation Key which is set as the universal default.  If an activation "
"key is set\n"
"    on the account as a universal default, you can disable this key and "
"retry to avoid\n"
"    requiring a Management entitlement."
msgstr ""
