# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# George Machitidze <giomac@gmail.com>, 2012.
# George Machitidze <giomac@gmail.com>, 2012
# Jan Dobes <jdobes@redhat.com>, 2016. #zanata
# Jiri Dostal <jdostal@redhat.com>, 2018. #zanata
msgid ""
msgstr ""
"Project-Id-Version: Spacewalk\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-04-08 15:54+0200\n"
"PO-Revision-Date: 2023-02-13 22:14+0000\n"
"Last-Translator: Temuri Doghonadze <temuri.doghonadze@gmail.com>\n"
"Language-Team: Georgian <https://l10n.opensuse.org/projects/uyuni/spacewalk-"
"client-tools/ka/>\n"
"Language: ka\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Generator: Weblate 4.9.1\n"

#: ../src/up2date_client/capabilities.py:94
#, python-format
msgid ""
"This client requires the server to support %s, which the current server does "
"not support"
msgstr ""

#: ../src/up2date_client/config.py:162
#, python-format
msgid "%s was not found"
msgstr "%s ვერ მოძებნა"

#: ../src/up2date_client/rpcServer.py:56
msgid "Error: Server Unavailable. Please try later."
msgstr "შეცდინა: სერვერი მიუწვდომელია. გთხოვთ მოგვიანებით კვლავ სცადოთ."

#: ../src/up2date_client/rpcServer.py:182
msgid "ERROR: can not find server CA file"
msgstr ""

#: ../src/up2date_client/rpcServer.py:220
msgid "Connection aborted by the user"
msgstr "დაკავშირება შეწყდა მომხმარებლის მიერ"

#: ../src/up2date_client/rpcServer.py:268
msgid "Server has refused connection due to high load"
msgstr "დიდი დატვირთვის გამო სერვერმა უარყო კავშირი"

#: ../src/up2date_client/up2dateErrors.py:47
#: ../src/up2date_client/up2dateErrors.py:80
#, python-format
msgid "class %s has no attribute '%s'"
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:107
msgid "RPM error.  The message was:\n"
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:114
msgid "Password error. The message was:\n"
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:118
msgid "RPM dependency error. The message was:\n"
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:128
msgid "Error communicating with server. The message was:\n"
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:135
msgid "File Not Found: \n"
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:142
msgid "Delay error from server.  The message was:\n"
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:178
msgid "Error validating data at server:\n"
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:191
msgid ""
"\n"
"Red Hat Network Classic is not supported.\n"
"    "
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:197
msgid "The installation number is invalid"
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:200
msgid "Error parsing the oemInfo file at field:\n"
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:227
msgid "Network error: "
msgstr "ქსელის შეცდომა: "

#: ../src/up2date_client/up2dateErrors.py:295
msgid ""
"\n"
"    Your organization does not have enough Management entitlements to "
"register this\n"
"    system. Please notify your organization administrator of this error.\n"
"    You should be able to register this system after your organization frees "
"existing\n"
"    or purchases additional entitlements. Additional entitlements may be "
"purchased by your\n"
"    organization administrator in the SUSE Customer Center.\n"
"\n"
"    A common cause of this error code is due to having mistakenly setup an\n"
"    Activation Key which is set as the universal default.  If an activation "
"key is set\n"
"    on the account as a universal default, you can disable this key and "
"retry to avoid\n"
"    requiring a Management entitlement."
msgstr ""
