# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# , 2012.
msgid ""
msgstr ""
"Project-Id-Version: Spacewalk\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-04-08 15:54+0200\n"
"PO-Revision-Date: 2013-02-06 09:40+0000\n"
"Last-Translator: adelton <jpx-tx@adelton.com>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: zh_TW.Big5\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: ../src/up2date_client/capabilities.py:94
#, python-format
msgid ""
"This client requires the server to support %s, which the current server does "
"not support"
msgstr "這個用戶端需要支援 %s 的伺服器，然而目前的伺服器並不支援"

#: ../src/up2date_client/config.py:162
#, python-format
msgid "%s was not found"
msgstr "找不到 %s"

#: ../src/up2date_client/rpcServer.py:56
msgid "Error: Server Unavailable. Please try later."
msgstr ""

#: ../src/up2date_client/rpcServer.py:182
#, fuzzy
msgid "ERROR: can not find server CA file"
msgstr "錯誤：無法找到 RHNS CA 檔"

#: ../src/up2date_client/rpcServer.py:220
msgid "Connection aborted by the user"
msgstr "連線被使用者中斷"

#: ../src/up2date_client/rpcServer.py:268
msgid "Server has refused connection due to high load"
msgstr "由於負載太大，伺服器拒絕連線"

#: ../src/up2date_client/up2dateErrors.py:47
#: ../src/up2date_client/up2dateErrors.py:80
#, python-format
msgid "class %s has no attribute '%s'"
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:107
msgid "RPM error.  The message was:\n"
msgstr "RPM 錯誤。 錯誤訊息是：\n"

#: ../src/up2date_client/up2dateErrors.py:114
msgid "Password error. The message was:\n"
msgstr "密碼錯誤。 錯誤訊息是：\n"

#: ../src/up2date_client/up2dateErrors.py:118
msgid "RPM dependency error. The message was:\n"
msgstr "RPM 相依性發生錯誤，錯誤訊息是：\n"

#: ../src/up2date_client/up2dateErrors.py:128
msgid "Error communicating with server. The message was:\n"
msgstr "連接伺服器時發生錯誤，錯誤訊息是：\n"

#: ../src/up2date_client/up2dateErrors.py:135
msgid "File Not Found: \n"
msgstr "找不到檔案： \n"

#: ../src/up2date_client/up2dateErrors.py:142
msgid "Delay error from server.  The message was:\n"
msgstr "從伺服器傳來的延遲錯誤。 錯誤訊息是：\n"

#: ../src/up2date_client/up2dateErrors.py:178
msgid "Error validating data at server:\n"
msgstr "伺服器驗證資料時發生錯誤：\n"

#: ../src/up2date_client/up2dateErrors.py:191
#, fuzzy
msgid ""
"\n"
"Red Hat Network Classic is not supported.\n"
"    "
msgstr "Red Hat Network 的位置（_L）"

#: ../src/up2date_client/up2dateErrors.py:197
msgid "The installation number is invalid"
msgstr "安裝號碼不符"

#: ../src/up2date_client/up2dateErrors.py:200
msgid "Error parsing the oemInfo file at field:\n"
msgstr "解析 oeminfo 檔案中的欄位時發生錯誤：\n"

#: ../src/up2date_client/up2dateErrors.py:227
msgid "Network error: "
msgstr ""

#: ../src/up2date_client/up2dateErrors.py:295
msgid ""
"\n"
"    Your organization does not have enough Management entitlements to "
"register this\n"
"    system. Please notify your organization administrator of this error.\n"
"    You should be able to register this system after your organization frees "
"existing\n"
"    or purchases additional entitlements. Additional entitlements may be "
"purchased by your\n"
"    organization administrator in the SUSE Customer Center.\n"
"\n"
"    A common cause of this error code is due to having mistakenly setup an\n"
"    Activation Key which is set as the universal default.  If an activation "
"key is set\n"
"    on the account as a universal default, you can disable this key and "
"retry to avoid\n"
"    requiring a Management entitlement."
msgstr ""

#, fuzzy
#~ msgid "Warning: unable to enable rhnsd with systemd"
#~ msgstr "警告： 無法使用 chkconfig 來啟用 rhnsd"

#~ msgid "Warning: unable to enable rhnsd with chkconfig"
#~ msgstr "警告： 無法使用 chkconfig 來啟用 rhnsd"
